'''
Created on Oct 13, 2014

@author: Richard
'''
DISPLAY_CAPTION = "Slayer"
DISPLAY_ICON = "icon.gif"
DISPLAY_DOUBLE_BUFFERED = True
DISPLAY_RESIZABLE = False
DISPLAY_CLOCK_TICKS = 30
DISPLAY_GRID_ROWS = 10
DISPLAY_GRID_COLS = 10
